using System.Linq;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.OSXStandalone;
using UnityEngine;

namespace Jacquard.Editor {

// The two desktop players, as calls a command line can make.
//
// They are two entry points and not one because the platforms cannot agree on a scripting
// backend, and the reason is the host rather than a preference: IL2CPP hands the C++ it
// generates to the target's own toolchain, and Unity ships no cross-compiler for it — the
// macOS editor is offered `windows-mono` and there is no `windows-il2cpp` to install. So a
// Mac can produce a Windows player under Mono and under nothing else, while its own player
// is IL2CPP, which is what iOS already ships and what keeps the notarised bundle clear of
// the two entitlements a JIT has to ask for.
//
// The backend is written here, in the build, rather than held in a Build Profile, because a
// profile cannot say it: BuildProfile's scripting surface is scenes, defines and components,
// and the player settings behind an override are reachable only from the Build Profiles
// window. A setting only a hand can write is a setting this project cannot build from a
// command line, which is the one thing the project is meant to be able to do. So each entry
// point writes the backend it needs and puts back whatever it found, and the value sitting
// in ProjectSettings governs the editor alone and nothing that ships.
//
// The Mac player is arm64 alone. A Universal bundle would carry an x86_64 slice for machines
// this app is never built on, never run on and never measured on — the whole of what is known
// about how it performs was learned on Apple silicon — and it would charge every reader who
// is on Apple silicon the size of that slice to carry it. An Intel Mac is better told plainly
// that there is no build for it than handed one nobody has ever opened; the archive is named
// for the chip so that the telling happens before the download rather than after.
//
// The scenes are whatever the build settings hold, in their order, the same as BuildIos: one
// scene generated by SceneBuilder, read from there rather than named, so that a scene has one
// place it is registered.
//
// What comes out is a player and not an archive. The signing, the notarisation and the
// packaging belong to Tools/release.sh, which owns them for both platforms; this is only the
// part Unity can do.

static class BuildDesktop
{
    // Beside the assets and out of the repository — `.gitignore` carries `/Build`. Both live
    // under one root so that release.sh can find them without being told twice.
    const string MacOutput = "Build/macOS/Jacquard.app";
    const string WindowsOutput = "Build/Windows/Jacquard.exe";

    [MenuItem("Jacquard/Build macOS")]
    public static void BuildMac()
    {
        // Written on every build rather than left to whatever the last build set, since this
        // lives in UserSettings and x64 is what a fresh clone would otherwise build.
        UserBuildSettings.architecture = OSArchitecture.ARM64;

        Build(BuildTarget.StandaloneOSX, ScriptingImplementation.IL2CPP, MacOutput);
    }

    [MenuItem("Jacquard/Build Windows")]
    public static void BuildWindows()
        => Build(BuildTarget.StandaloneWindows64, ScriptingImplementation.Mono2x, WindowsOutput);

    static void Build(BuildTarget target, ScriptingImplementation backend, string output)
    {
        var scenes = EditorBuildSettings.scenes.Where(s => s.enabled)
                                              .Select(s => s.path).ToArray();

        // One setting covers Windows, macOS and Linux together — NamedBuildTarget.Standalone
        // is the whole desktop group — so the two builds would overwrite each other's answer
        // if either left its own behind.
        var found = PlayerSettings.GetScriptingBackend(NamedBuildTarget.Standalone);
        PlayerSettings.SetScriptingBackend(NamedBuildTarget.Standalone, backend);

        try
        {
            var options = new BuildPlayerOptions {
                scenes = scenes,
                locationPathName = output,
                target = target,
                options = BuildOptions.None };

            var report = BuildPipeline.BuildPlayer(options);
            var summary = report.summary;

            Debug.Log($"BuildDesktop: {summary.result} in {summary.totalTime}, " +
                      $"{summary.totalErrors} errors, {summary.totalWarnings} warnings, " +
                      $"{backend} to {summary.outputPath}");

            // Batch mode reads the exit code and nothing else, so a failure has to say so
            // that way rather than only in the log.
            if (summary.result != BuildResult.Succeeded && Application.isBatchMode)
                EditorApplication.Exit(1);
        }
        finally
        {
            PlayerSettings.SetScriptingBackend(NamedBuildTarget.Standalone, found);
        }
    }
}

} // namespace Jacquard.Editor
