using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Jacquard.Editor {

// The iOS build, as one call a command line can make.
//
// Unity has no built-in command-line build for this platform — only the desktop targets
// build from flags alone — so a project meant to be driveable without a hand on the
// editor needs an entry point of its own, and this is it.
//
// It writes the generated Xcode project to `Xcode` beside the assets, appending rather
// than replacing so that a second build is incremental: a clean iOS build here is the
// il2cpp pass over every assembly, and thirteen seconds against several minutes is the
// difference between a loop that can be run and one that will not be.
//
// The scenes are whatever the build settings hold, in their order, which is one scene
// generated by SceneBuilder. Reading them from there rather than naming one keeps this
// from being a second place a scene has to be registered.
//
// What comes out is an Xcode project and not an archive: the signing, the archive and
// the upload belong to the tools that own them, and this is only the part Unity can do.

static class BuildIos
{
    [MenuItem("Jacquard/Build iOS")]
    public static void Build()
    {
        var scenes = EditorBuildSettings.scenes.Where(s => s.enabled)
                                              .Select(s => s.path).ToArray();

        var options = new BuildPlayerOptions {
            scenes = scenes,
            locationPathName = "Xcode",
            target = BuildTarget.iOS,
            options = BuildOptions.AcceptExternalModificationsToPlayer };

        var report = BuildPipeline.BuildPlayer(options);
        var summary = report.summary;

        Debug.Log($"BuildIos: {summary.result} in {summary.totalTime}, " +
                  $"{summary.totalErrors} errors, {summary.totalWarnings} warnings, " +
                  $"{scenes.Length} scene(s) to {summary.outputPath}");

        // Batch mode reads the exit code and nothing else, so a failure has to say so
        // that way rather than only in the log.
        if (summary.result != BuildResult.Succeeded && Application.isBatchMode)
            EditorApplication.Exit(1);
    }
}

} // namespace Jacquard.Editor
