using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Jacquard.Editor {

// The Android build, as one call a command line can make.
//
// It exists for the same reason BuildIos does and not for a second one: Unity builds only
// the three desktop targets from flags alone, and answers a command line asking for this
// one with "Target Android has no built-in command-line build". A project meant to be
// driveable without a hand on the editor therefore has to carry the entry point itself.
//
// What it writes is an APK and not an app bundle. A bundle is what a store takes and an
// APK is what a device or an emulator can be handed directly, and handing one to a device
// is the whole of what this is for so far — `buildAppBundle` is written on every build
// rather than trusted, because it lives in EditorUserBuildSettings, outside the
// repository, and one trip through the Build Profiles window is enough to flip it for
// good. The same trap the two desktop architectures are written against in BuildDesktop.
//
// Nothing else here is set, and that is deliberate: the backend, the architecture and the
// stripping are already Android's own entries in ProjectSettings — IL2CPP, ARM64, High —
// so unlike the desktop pair there is no group two targets have to share and nothing to
// put back afterwards. ARM64 alone also covers the emulator on an Apple silicon Mac,
// which reports `arm64-v8a` like the phones do.
//
// Signing is Unity's debug keystore, since `androidUseCustomKeystore` is off. That is
// enough to install and run, and not enough to publish — a release that goes anywhere
// near a store needs a key this file does not have and should not hold.
//
// The scenes are whatever the build settings hold, in their order, the same as the other
// two entry points: one scene generated by SceneBuilder, read from there rather than
// named, so that a scene has one place it is registered.

static class BuildAndroid
{
    // Beside the other players and out of the repository — `.gitignore` carries `/Build`.
    const string Output = "Build/Android/Jacquard.apk";

    [MenuItem("Jacquard/Build Android")]
    public static void Build()
    {
        var scenes = EditorBuildSettings.scenes.Where(s => s.enabled)
                                              .Select(s => s.path).ToArray();

        EditorUserBuildSettings.buildAppBundle = false;

        var options = new BuildPlayerOptions {
            scenes = scenes,
            locationPathName = Output,
            target = BuildTarget.Android,
            options = BuildOptions.None };

        var report = BuildPipeline.BuildPlayer(options);
        var summary = report.summary;

        Debug.Log($"BuildAndroid: {summary.result} in {summary.totalTime}, " +
                  $"{summary.totalErrors} errors, {summary.totalWarnings} warnings, " +
                  $"{scenes.Length} scene(s) to {summary.outputPath}");

        // Batch mode reads the exit code and nothing else, so a failure has to say so
        // that way rather than only in the log.
        if (summary.result != BuildResult.Succeeded && Application.isBatchMode)
            EditorApplication.Exit(1);
    }
}

} // namespace Jacquard.Editor
