using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Jacquard.Editor {

// The Android build, as two calls a command line can make.
//
// It exists for the same reason BuildIos does and not for a second one: Unity builds only
// the three desktop targets from flags alone, and answers a command line asking for this
// one with "Target Android has no built-in command-line build". A project meant to be
// driveable without a hand on the editor therefore has to carry the entry point itself.
//
// Two of them, because a bundle is what a store takes and an APK is what a device or an
// emulator can be handed directly, and neither stands in for the other: Play has taken
// nothing but an app bundle from a new app since 2021, and `adb install` takes nothing but
// an APK. Handing one to a device was the whole of what this file was for until the store
// entered it. So `buildAppBundle` is written on every build rather than trusted, because
// it lives in EditorUserBuildSettings, outside the repository, and one trip through the
// Build Profiles window is enough to flip it for good — the same trap the two desktop
// architectures are written against in BuildDesktop.
//
// Nothing else about the player is set here, and that is deliberate: the backend, the
// architecture and the stripping are already Android's own entries in ProjectSettings —
// IL2CPP, ARM64, High — so unlike the desktop pair there is no group two targets have to
// share and nothing to put back afterwards. ARM64 alone also covers the emulator on an
// Apple silicon Mac, which reports `arm64-v8a` like the phones do.
//
// The scenes are whatever the build settings hold, in their order, the same as the other
// two entry points: one scene generated by SceneBuilder, read from there rather than
// named, so that a scene has one place it is registered.

static class BuildAndroid
{
    // Beside the other players and out of the repository — `.gitignore` carries `/Build`.
    const string ApkOutput = "Build/Android/Jacquard.apk";
    const string AabOutput = "Build/Android/Jacquard.aab";

    // Where the upload key is read from, and why it is read rather than held.
    //
    // Unity keeps signing in ProjectSettings, and neither half of it can live there. The
    // keystore is one machine's file, so `AndroidKeystoreName` — a tracked field — would
    // carry a path that is true on this Mac and false everywhere else; the password is
    // nobody's to commit at all. It is the buildAppBundle trap one step worse, because a
    // preference a window flipped costs a wrong build and a secret in a tracked file costs
    // a key that has to be replaced.
    //
    // So the build writes all of it from the environment and puts back what it found, and
    // what sits in ProjectSettings stays empty and governs nothing that ships.
    //
    // One password and not two, which is the file's own doing rather than a simplification
    // here: keytool has written PKCS12 since JDK 9, and PKCS12 holds a single password for
    // the store and the key together. Handed a `-keypass` that differs from the store's it
    // says so and drops it — "Different store and key passwords not supported for PKCS12
    // KeyStores. Ignoring user-specified -keypass value." Unity's two fields are therefore
    // set from the one variable, because one is what the keystore actually contains.
    const string KeystoreVar = "JACQUARD_UPLOAD_KEYSTORE";
    const string AliasVar = "JACQUARD_UPLOAD_ALIAS";
    const string PasswordVar = "JACQUARD_UPLOAD_PASSWORD";

    [MenuItem("Jacquard/Build Android")]
    public static void BuildApk() => Build(false, ApkOutput);

    [MenuItem("Jacquard/Build Android Bundle")]
    public static void BuildBundle() => Build(true, AabOutput);

    static void Build(bool bundle, string output)
    {
        var scenes = EditorBuildSettings.scenes.Where(s => s.enabled)
                                              .Select(s => s.path).ToArray();

        EditorUserBuildSettings.buildAppBundle = bundle;

        // The APK is signed with Unity's debug keystore, since `androidUseCustomKeystore`
        // is off in ProjectSettings. That is enough to install and run, and installing and
        // running is all the APK is for. A bundle is going to a store, so it has to carry
        // the upload key instead — Play names debug mode when it turns one down.
        var found = default(Signing);

        if (bundle)
        {
            if (!ReadUploadKey(out var key)) return;

            found = Signing.Read();
            key.Write();
        }

        try
        {
            var options = new BuildPlayerOptions {
                scenes = scenes,
                locationPathName = output,
                target = BuildTarget.Android,
                options = BuildOptions.None };

            var report = BuildPipeline.BuildPlayer(options);
            var summary = report.summary;

            Debug.Log($"BuildAndroid: {summary.result} in {summary.totalTime}, " +
                      $"{summary.totalErrors} errors, {summary.totalWarnings} warnings, " +
                      $"{scenes.Length} scene(s) to {summary.outputPath}");

            // Batch mode reads the exit code and nothing else, so a failure has to say so
            // that way rather than only in the log.
            if (summary.result != BuildResult.Succeeded && Application.isBatchMode)
                EditorApplication.Exit(1);
        }
        finally
        {
            if (bundle) found.Write();
        }
    }

    // What ProjectSettings held before a bundle build wrote the key into it, so that the
    // password is out of the settings object again before anything can save it. The build
    // is where it has to be put back rather than on quit: a batch mode editor writes
    // ProjectSettings on its way out, and an editor a person is sitting in front of writes
    // it whenever it feels like it.
    //
    // It is a restore and not a round trip, because one of these values does not survive
    // one. `keystoreName` normalises what it is handed, so writing back the empty string a
    // fresh clone reads leaves `AndroidKeystoreName: '{inproject}: '` in the file rather
    // than the empty it started as — Unity's way of spelling a project-relative path with
    // nothing after it. That is committed at the normalised value, since it is what the
    // first bundle build on any tree writes and it holds neither a path nor a secret: two
    // builds of the same tree were compared and the file came out byte for byte identical.
    struct Signing
    {
        bool _custom;
        string _keystore, _alias, _keystorePass, _aliasPass;

        public static Signing Read()
            => new Signing {
                _custom = PlayerSettings.Android.useCustomKeystore,
                _keystore = PlayerSettings.Android.keystoreName,
                _alias = PlayerSettings.Android.keyaliasName,
                _keystorePass = PlayerSettings.Android.keystorePass,
                _aliasPass = PlayerSettings.Android.keyaliasPass };

        public static Signing UploadKey(string keystore, string alias, string password)
            => new Signing {
                _custom = true,
                _keystore = keystore,
                _alias = alias,
                _keystorePass = password,
                _aliasPass = password };

        public void Write()
        {
            PlayerSettings.Android.useCustomKeystore = _custom;
            PlayerSettings.Android.keystoreName = _keystore;
            PlayerSettings.Android.keyaliasName = _alias;
            PlayerSettings.Android.keystorePass = _keystorePass;
            PlayerSettings.Android.keyaliasPass = _aliasPass;
        }
    }

    // Everything wrong with the environment is worth saying in one message rather than one
    // at a time, since the three variables are set together or not at all and a release is
    // rare enough that nobody remembers their names.
    static bool ReadUploadKey(out Signing key)
    {
        key = default;

        var keystore = Environment.GetEnvironmentVariable(KeystoreVar);
        var alias = Environment.GetEnvironmentVariable(AliasVar);
        var password = Environment.GetEnvironmentVariable(PasswordVar);

        var missing = new[] { (KeystoreVar, keystore),
                              (AliasVar, alias),
                              (PasswordVar, password) }
                      .Where(v => string.IsNullOrEmpty(v.Item2))
                      .Select(v => v.Item1).ToArray();

        if (missing.Length > 0)
        {
            Fail($"a bundle has to be signed with the upload key, and " +
                 $"{string.Join(", ", missing)} {(missing.Length == 1 ? "is" : "are")} " +
                 $"not set. Docs/releasing.md says how the key is made and what to set.");
            return false;
        }

        // Gradle's own answer to a keystore that is not there names the file and not the
        // reason, and the reason is nearly always the variable rather than the key.
        if (!File.Exists(keystore))
        {
            Fail($"{KeystoreVar} is {keystore}, and there is no file there.");
            return false;
        }

        key = Signing.UploadKey(keystore, alias, password);
        return true;
    }

    static void Fail(string message)
    {
        Debug.LogError($"BuildAndroid: {message}");
        if (Application.isBatchMode) EditorApplication.Exit(1);
    }
}

} // namespace Jacquard.Editor
